### ISSUE TITLE
Suggestion: Change Title color

### ISSUE THREAD

**Issue by egmoura1981** [egmoura1981/github-crash-course#1]
I think it look better if the main title is a bit more orange

The styling rule could be changed like this:

```css
h1{
  color:#efa82e;
}
```
